project:
  type: website
  output-dir: _site

website:
  title: "EC5230 Industrial Organisation"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lectures"
        file: lecture-slides/index.qmd
      - text: "Exercises"
        href: exercises/
      - text: "Apps"
        href: apps/

execute:
  freeze: false

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false


