project:
  type: website
  output-dir: _site

author: "Gerhard Riener"
lang: en-GB
description: "MSc-level Industrial Organisation course at the University of St Andrews"

website:
  title: "EC5230 Industrial Organisation"
  # site-url: "https://gerhardriener.github.io/EC5230-industrial-organisation/"
  description: "MSc-level Industrial Organisation course at the University of St Andrews"

  navbar:
    background: "#00539b"
    foreground: "#ffffff"
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lectures"
        menu:
          - text: "All Lecture Slides"
            href: lecture-slides/index.qmd
          - text: "Week 0: Introduction"
            href: lecture-slides/slides/lecture-0-intro.qmd
          - text: "Week 1: Oligopoly"
            href: lecture-slides/slides/lecture-1-oligopoly.qmd
          - text: "Week 2: Product Differentiation"
            href: lecture-slides/slides/lecture-2-product-differentiation.qmd
          - text: "Week 3: Innovation"
            href: lecture-slides/slides/lecture-3-innovation.qmd
          - text: "Week 4: Patents and IPRs"
            href: lecture-slides/slides/lecture-4-patents.qmd
          - text: "Week 5: Multi-stage Games"
            href: lecture-slides/slides/lecture-5-multi-stage-games.qmd
          - text: "Week 7: Cooperative R&D"
            href: lecture-slides/slides/lecture-6-corporate-rand.qmd
      - text: "Exercises"
        menu:
          - text: "All Exercises"
            href: exercises/index.qmd
          - text: "Exercise 1: Oligopoly and Product Differentiation"
            href: exercises/sheets/exercises-1.qmd
          - text: "Live Exercise 1: Hotelling (Quadratic Transport Costs)"
            href: exercises/live/live-exercise-1.qmd
          - text: "Exercise 2: Innovaton incentives & Patents"
            href: exercises/sheets/exercises-2.qmd
          - text: "Live Exercise 2a"
            href: exercises/live/live-exercise-2a.qmd
          - text: "Live Exercise 2b"
            href: exercises/live/live-exercise-2b.qmd

  sidebar:
    - id: lectures
      title: "Lecture Slides"
      style: "docked"
      background: light
      contents:
        - text: "Lecture Overview"
          href: lecture-slides/index.qmd
        # BEGIN AUTO-LECTURE-SIDEBAR
        - section: "Week 0"
          contents:
            - lecture-slides/slides/lecture-0-intro.qmd
        - section: "Week 1"
          contents:
            - lecture-slides/slides/lecture-1-oligopoly.qmd
        - section: "Week 2"
          contents:
            - lecture-slides/slides/lecture-2-product-differentiation.qmd
        - section: "Week 3"
          contents:
            - lecture-slides/slides/lecture-3-innovation.qmd
        - section: "Week 4"
          contents:
            - lecture-slides/slides/lecture-4-patents.qmd
        - section: "Week 5"
          contents:
            - lecture-slides/slides/lecture-5-multi-stage-games.qmd
        - section: "Week 7"
          contents:
            - lecture-slides/slides/lecture-6-corporate-rand.qmd
        # END AUTO-LECTURE-SIDEBAR
    - id: exercises
      title: "Exercises"
      style: "docked"
      background: light
      contents:
        - exercises/index.qmd
        - section: "Exercise Sheets"
          contents:
            - exercises/sheets/exercises-1.qmd
            - exercises/sheets/exercises-2.qmd
        - section: "Live Exercises"
          contents:
            - exercises/live/live-exercise-1.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    link-external-newwindow: true

bibliography: references.bib
biblio-style: chicago-author-date

execute:
  python: ".venv/Scripts/python.exe"
  echo: false
  warning: false
  message: false
