project:
  type: website
  output-dir: _site

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "EC5230 Industrial Organisation"
  navbar:
    title: "EC5230"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        href: lecture-slides/index.qmd
      - text: "Exercises"
        href: exercises/index.qmd

  sidebar:
    - id: lectures
      title: "Lecture Slides"
      contents:
        - lecture-slides/lecture-1-oligopoly.qmd
        - lecture-slides/lecture-2-product-differentiation.qmd

