project:
  type: website
  output-dir: _site

author: "Gerhard Riener"
lang: en-GB
description: "MSc-level Industrial Organisation course at the University of St Andrews"

website:
  title: "EC5230 Industrial Organisation"
  # site-url: "https://gerhardriener.github.io/EC5230-industrial-organisation/"
  description: "MSc-level Industrial Organisation course at the University of St Andrews"

  navbar:
    background: "#00539b"
    foreground: "#ffffff"
    left:
      - text: "Home"
        file: index.qmd
      - text: "Exercises"
        href: exercises/index.qmd
  sidebar:
    # BEGIN AUTO-LECTURE-SIDEBAR
    - title: "Lecture Slides"
      style: "docked"
      background: light
      contents:
        - section: "Week 0"
          contents:
            - lecture-slides/slides/lecture-0-intro.qmd
        - section: "Week 1"
          contents:
            - lecture-slides/slides/lecture-1-oligopoly.qmd
        - section: "Week 2"
          contents:
            - lecture-slides/slides/lecture-2-product-differentiation.qmd
        - section: "Week 3"
          contents:
            - lecture-slides/slides/lecture-3-innovation.qmd
        - section: "Week 4"
          contents:
            - lecture-slides/slides/lecture-4-patents.qmd
        - section: "Week 5"
          contents:
            - lecture-slides/slides/lecture-5-repeated-games.qmd
        - section: "Week 7"
          contents:
            - lecture-slides/slides/lecture-6-corporate-rand.qmd
    # END AUTO-LECTURE-SIDEBAR

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    link-external-newwindow: true

bibliography: references.bib
biblio-style: chicago-author-date

execute:
  python: ".venv/Scripts/python.exe"
  echo: false
  warning: false
  message: false
