project:
  type: website
  output-dir: _site

author: "Gerhard Riener"
lang: en-GB
description: "MSc-level Industrial Organisation course at the University of St Andrews"

website:
  title: "EC5230 Industrial Organisation"
  site-url: "https://gerhardriener.github.io/EC5230-industrial-organisation/"
  description: "MSc-level Industrial Organisation course at the University of St Andrews"

  navbar:
    background: "#00539b"
    foreground: "#ffffff"
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lectures"
        file: lecture-slides/index.qmd
      - text: "Exercises"
        href: exercises/
  sidebar:
    - title: "Lecture Slides"
      style: "docked"
      background: light
      contents:
        - section: "Weeks 1-5"
          contents:
            - lecture-slides/lecture-1-oligopoly.qmd
            - lecture-slides/lecture-2-product-differentiation.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    link-external-newwindow: true


bibliography: references.bib
biblio-style: chicago-author-date

execute:
  python: ".venv/Scripts/python.exe"
  echo: false
  warning: false
  message: false
