project:
  type: default
  output-dir: .
  execute-dir: project

execute:
  freeze: false
  cache: false
  warning: false
  error: false
  message: false

format:
  html:
    keep-md: false
    self-contained: false
